### ISSUE TITLE
404 after creating/editing topics or pages containing special characters

### ISSUE THREAD

**Issue by thibautsergent** [docpht/docpht#18]
## Expected Behavior
No 404 errors after creating/editing topics or pages containing special characters

## Actual Behavior
Big mess with topics/pages name containing special characters : 
- when topic is starting with # : not opening at all
- others special characters cause 404 errors after creating or editing topics/pages

## Steps to Reproduce the Problem

  1. Create a new topic starting with #
  2. Clicking on the topic will not open it

and : 
 
  1. Create a new topic/page containing special characters
  2. Just after clicking the button "create", redirect to 404
  3. Topic/Page is created and can be browsed from the menu
  4. When editing this topic/page, redirected to 404 after saving edits

## Specifications

  - DocPHT version: 1.3.2
  - PHP version: 7.4
  - Platform: apache/2.4.41
  - OS: ubuntu
  - Browser: firefox 81

**Comment by quangbahoa** [comment]
Yea,
Same problem.

**Comment by creecros** [comment]
Yea, I tested it and had same issue. I need to refamiliarize myself with the code, haven't looked at it since I wrote it.

Do we want special characters in the titles? Or should I just remove them completely?

**Comment by quangbahoa** [comment]
Special/non-english characters should be allowed.

**Comment by thibautsergent** [comment]
> Special/non-english characters should be allowed.

In french there is a lot of accented characters like "é è à ô ô î ï" etc.. So it will be great if it's allowed

**Comment by creecros** [comment]
came up with a simple solution, which appears to have completely solved the issue, but it affects the front end, which was poor planning on our part, because as I am going through fixing the locations i can find, i keep thinking to myself, "why the heck didn't we do it like this to begin with"....so I want you to know I am working on it, but i'm not really the front end guy, and I have no idea where @kenlog  is. maybe he will pop in and say hi, and I can explain the issues to him.

Otherwise, just bear with me, as I search the code for all the areas that it effects.

**Comment by creecros** [comment]
@kenlog @thibautsergent @quangbahoa 

https://github.com/creecros/docpht

If you guys wouldn't mind helping test for me, I think this covers it, but always nice to have others play with it. I will merge once I feel like nothing was overlooked, and I know I'm a bad tester. The new code should be compatible with any old data, but, I suggest backing up just in case.

@kenlog 

What I did:
1.) switched the slug creation to use the unique ID, instead of "topic/filename"
2.) changed every instance there was a redirect using "topic/filename" to getSlug
3.) moved the sidebar to render in the footer, because $_SESSION['page_id'] was not yet available in the header
4.) new pageModel method to findkeyfrompath, implemented in pageModel->getId($path)
5.) utilized getId($path) in the one instance I need the id before render
6.) clear the $_SESSION['page_id'] when going to HomePageController, thus clearing the sidebar active menus when returning to home
7.) utilized the id and pageModel to get active menu item, instead of parsing the URI

about sums it up.

Should allow special characters now, since all folders and filenames will be based off the unique id, and not based off the topic/filename where the special chars reside. Tested using french chars like  "é" and had no issue in the topic or filename. works with previous data, however if the data was previously corrupted, it will not fix the issue. 

I should probably look at updates to the docker image as well before a new release.

**Comment by quangbahoa** [comment]
@creecros 

Got some errors

```
Warning: file_put_contents(): Filename cannot be empty in C:\laragon4\www\docpht\src\model\PageModel.php on line 433
Warning: file_put_contents(): Filename cannot be empty in C:\laragon4\www\docpht\src\model\PageModel.php on line 433
Notice: Trying to access array offset on value of type null in C:\laragon4\www\docpht\src\model\PageModel.php on line 245
Notice: Trying to access array offset on value of type null in C:\laragon4\www\docpht\src\model\PageModel.php on line 245
Notice: Trying to access array offset on value of type null in C:\laragon4\www\docpht\src\model\PageModel.php on line 245
Warning: file_put_contents(): Filename cannot be empty in C:\laragon4\www\docpht\src\model\PageModel.php on line 433
Notice: Trying to access array offset on value of type null in C:\laragon4\www\docpht\src\model\PageModel.php on line 245
Notice: Trying to access array offset on value of type null in C:\laragon4\www\docpht\src\model\PageModel.php on line 245
Notice: Trying to access array offset on value of type null in C:\laragon4\www\docpht\src\model\PageModel.php on line 245
Warning: Invalid argument supplied for foreach() in C:\laragon4\www\docpht\src\lib\DocBuilder.php on line 178
Fatal error: Uncaught TypeError: pathinfo() expects parameter 1 to be string, null given in C:\laragon4\www\docpht\src\lib\DocBuilder.php:192 Stack trace: #0 C:\laragon4\www\docpht\src\lib\DocBuilder.php(192): pathinfo(NULL, 1) #1 C:\laragon4\www\docpht\src\forms\CreatePageForm.php(106): DocPHT\Lib\DocBuilder->buildPhpPage('5f87babc24e31') #2 C:\laragon4\www\docpht\src\controller\FormPageController.php(23): DocPHT\Form\CreatePageForm->create() #3 [internal function]: DocPHT\Controller\FormPageController->getCreatePageForm() #4 C:\laragon4\www\docpht\vendor\nezamy\route\system\Route.php(651): call_user_func_array(Array, Array) #5 C:\laragon4\www\docpht\vendor\nezamy\route\system\Route.php(598): System\Route->callback(Array, Array) #6 C:\laragon4\www\docpht\index.php(92): System\Route->end() #7 {main} thrown in C:\laragon4\www\docpht\src\lib\DocBuilder.php on line 192
```

After try submit new non-english content all content either was gone.
- Screencast https://screencast-o-matic.com/watch/cY6oeh7FVj

**Comment by creecros** [comment]
@quangbahoa 

Awesome, thanks for testing, ill look at it tomorrow again, about to fall asleep 😴 tonight

**Comment by quangbahoa** [comment]
> @quangbahoa
> 
> Awesome, thanks for testing, ill look at it tomorrow again, about to fall asleep 😴 tonight

Good night! I'm 10AM ^^!

**Comment by creecros** [comment]
What am I missing?

http://somup.com/cY6oe3lk6w

**Comment by creecros** [comment]
@quangbahoa 

I didnt change anything, you sure you are using the latest code from my repo? Is it possible your PHP is cached? Have you restarted your server since updating the code? Your error messages seem to suggest its the previous code.

**Comment by creecros** [comment]
Never mind, you definitely are using the latest code. I'll try again to replicate tomorrow. Definitely need to sleep.

**Comment by creecros** [comment]
Tried again, and I can't reproduce your error:
![image](https://user-images.githubusercontent.com/26339368/96142148-bc978d80-0ecf-11eb-8dd7-efdbba8ff8ea.png)
Are you using PHP 7.4, I am suspecting that's the issue now.

**Comment by quangbahoa** [comment]
@creecros  PHP 7.4 with NGINX.

**Comment by creecros** [comment]
I just re tested using NGINX and PHP 7.4, I still can't break it:

![image](https://user-images.githubusercontent.com/26339368/96146921-d12a5480-0ed4-11eb-9514-0c6c7c7b3c7e.png)


![image](https://user-images.githubusercontent.com/26339368/96147013-eacb9c00-0ed4-11eb-983b-b176e7ebe610.png)

**Comment by creecros** [comment]
But, while you are there, just double check for me, that PHP cache is turned off.

Go to etc/php7/conf.d/local.ini

turn on validate timestamps and set revalidate frequency to 0. or just copy this ini:

```
extension = fileinfo
expose_php = Off
error_reporting = E_ALL
display_errors = Off
log_errors = On
error_log = /dev/stderr
date.timezone = UTC
allow_url_fopen = On
post_max_size = 32M
upload_max_filesize = 32M
opcache.max_accelerated_files = 7963
opcache.validate_timestamps = On
opcache.save_comments = 0
opcache.load_comments = 0
opcache.fast_shutdown = 1
opcache.enable_file_override = On
opcache.revalidate_freq = 0
```

Then restart your server

just want to make sure its not feeding scripts from cache

**Comment by quangbahoa** [comment]
@creecros  My bad,

I think my Windows system config was break it. I'm also tested on a LEMP stack and it work well. https://docpht.leduyquang.com

**Comment by kenlog** [comment]
@thibautsergent 

Hi guys, I've been working on a bug fix. Anyone who wants can test by cloning this [branch](https://github.com/docpht/docpht/tree/special-chars) :factory_worker:

Thanks I look forward to feedback

**Comment by thibautsergent** [comment]
@kenlog 

There isn't 404 now. But few things : 
* special chars are not kept in sidebar and browser titles
* If we create a new topic "@test" and another one "$test", $test topic will be merged with @test


@creecros fix is good on these points. But UID in url doesn't make them memorizable

**Comment by creecros** [comment]
UID in the url is not necessary, it was just the easiest fix I could come up with at the time to prevent special chars in the filenames, and ensure uniqueness.

I'm not sure why there would be any conflicts with previous backup data, there shouldn't be, @kenlog maybe you could send me the previous backup you used for testing, and I can figure that out.

**Comment by thibautsergent** [comment]
still relevant. Thanks

**Comment by creecros** [comment]
> still relevant. Thanks

@kenlog where you go? Hope you haven't gotten sick!

**Comment by kenlog** [comment]
Hi @creecros at the moment I'm busy with other work projects. Anyway if you can follow this I would be really grateful! Otherwise I plan to take care of it as soon as I have the time available.

**Comment by kenlog** [comment]
:robot: :+1:
