### ISSUE TITLE
[Feature request] lower-case titles/pages

### ISSUE THREAD

**Issue by didli** [docpht/docpht#22]
First, thank you for docpht : it's basically everything I was searching for, and more ! Thank you !

Now just for some cosmetic suggestions :
Creating a page / title seems to automatically create them with first letter uppercase. Is there a way to prevent that or change this behavior ?

Why the buttons like "insert before / insert after" are not always visible (i can only see them as i pass the mouse over them) ? 
was it intentionnal ?

Anyway, thank you again for docpht.

**Comment by creecros** [comment]
> First, thank you for docpht : it's basically everything I was searching for, and more ! Thank you !
- Glad to hear!

> Now just for some cosmetic suggestions :
> Creating a page / title seems to automatically create them with first letter uppercase. Is there a way to prevent that or change this behavior ?
- Currently, no, but it could be done. Maybe we could address it in a future release. Unfortunately, for us, automatically capitalizing the first letter was more visually appealing, and we did not make such an option. We didn't even provide a simple way to "code" the option to adhere to user input, because by default, we actually are lowercasing everything first, and then capitalizing the first letter of the topic title. Any change we made now, would force all previous data to be lower case regardless of how it was input.

> Why the buttons like "insert before / insert after" are not always visible (i can only see them as i pass the mouse over them) ?
> was it intentionnal ?
- Again, it was more visually appealing to us, to not see the edit functions until hovering over them. This could also be changed, perhaps we could make it an option in the future.

> Anyway, thank you again for docpht.
- No problem, we had hoped for more community involvement, so future updates could be awhile, as I and kenlog are fairly busy at the moment.
